USE cloudrestwines;
START TRANSACTION;
INSERT INTO trainingattendance VALUES
('TRSE0004','EMP0007','COMPLETED',DATE_SUB(CURRENT_DATE,INTERVAL 60 DAY),DATE_ADD(CURRENT_DATE,INTERVAL 670 DAY),'COMPETENT');
SELECT 'PASS: valid completed training was accepted' AS testResult;
ROLLBACK;

